name: publish-maven

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:16-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}